services:
  - type: web
    name: fitness-club-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tbot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false