services:
  - type: worker
    name: residence-fitness-bot
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python tbot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
